/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SACHIN
 */
package Contact;
import Database.databaseConnection;
import java.sql.*;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.JOptionPane;



public class Contact extends javax.swing.JFrame {

    /**
     * Creates new form Contact
     */
    Connection con;
    Statement stmt;
    public Contact() {
        initComponents();
         this.con = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contact = new javax.swing.JLabel();
        phonenum = new javax.swing.JLabel();
        whatsappnum = new javax.swing.JLabel();
        emailname = new javax.swing.JLabel();
        fbname = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        contactno = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        emailn = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        sendbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        phoneimg = new javax.swing.JLabel();
        whatsappimg = new javax.swing.JLabel();
        emailimg = new javax.swing.JLabel();
        facebookimg = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contact Us");

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contact.setFont(new java.awt.Font("Sitka Text", 1, 48)); // NOI18N
        contact.setForeground(new java.awt.Color(51, 0, 51));
        contact.setText("Contact Us");
        contact.setAlignmentX(0.5F);
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 280, 70));

        phonenum.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        phonenum.setForeground(new java.awt.Color(0, 0, 51));
        phonenum.setText("077 7252525 / 071 6326345");
        jPanel1.add(phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 200, 30));

        whatsappnum.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        whatsappnum.setForeground(new java.awt.Color(0, 0, 51));
        whatsappnum.setText("077 7252525 / 071 6326345");
        jPanel1.add(whatsappnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, 30));

        emailname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        emailname.setForeground(new java.awt.Color(0, 0, 51));
        emailname.setText("travelerztour@gmail.com");
        jPanel1.add(emailname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 230, 20));

        fbname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fbname.setForeground(new java.awt.Color(0, 0, 51));
        fbname.setText("https://www.facebook.com/travelerz.tour.");
        jPanel1.add(fbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 300, -1));

        name.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 120, 30));

        contactno.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        contactno.setText("Contact No");
        jPanel1.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 120, 30));

        country.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        country.setText("Country");
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 120, 30));

        emailn.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        emailn.setText("Email");
        jPanel1.add(emailn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 120, 30));

        comment.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        comment.setText("Comment");
        jPanel1.add(comment, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 270, 30));

        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 270, 30));

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });
        jPanel1.add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 270, 30));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 270, 30));

        sendbtn.setBackground(new java.awt.Color(51, 0, 51));
        sendbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sendbtn.setForeground(new java.awt.Color(255, 204, 204));
        sendbtn.setText("SEND");
        sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnActionPerformed(evt);
            }
        });
        jPanel1.add(sendbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 120, 30));

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane2.setViewportView(txtComment);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 270, 90));

        phoneimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phone.jpg"))); // NOI18N
        jPanel1.add(phoneimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 30, 30));

        whatsappimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/whatsapp.jpg"))); // NOI18N
        jPanel1.add(whatsappimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 30, 30));

        emailimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.jpg"))); // NOI18N
        jPanel1.add(emailimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 30, 30));

        facebookimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/facebook.jpg"))); // NOI18N
        jPanel1.add(facebookimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 30, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(823, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void sendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnActionPerformed
         try
        {
            this.stmt = con.createStatement();
            String query, name, contactNo, country, email, comment;
            query = "insert into Contact(Name,ContactNo,Country,Email,Comment) values(?,?,?,?,?)"; 
            java.sql.PreparedStatement st = con.prepareStatement(query);
           name = txtName.getText();
           contactNo = txtContactNo.getText();
           country = txtCountry.getText();
           email = txtEmail.getText();
           comment = txtComment.getText();
           
            st.setString(1, name);
            st.setString(2, contactNo);
            st.setString(3, country);
            st.setString(4, email);
           st.setString(5, comment);
            int count = st.executeUpdate();
            
            System.out.println("Done "+ count);
            JOptionPane.showMessageDialog(this, "Send successfuly ! ","Success", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_sendbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel comment;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel contactno;
    private javax.swing.JLabel country;
    private javax.swing.JLabel emailimg;
    private javax.swing.JLabel emailn;
    private javax.swing.JLabel emailname;
    private javax.swing.JLabel facebookimg;
    private javax.swing.JLabel fbname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phoneimg;
    private javax.swing.JLabel phonenum;
    private javax.swing.JButton sendbtn;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel whatsappimg;
    private javax.swing.JLabel whatsappnum;
    // End of variables declaration//GEN-END:variables
}
