/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tour_Management_System;

import AboutUs.About;
import Contact.Contact;
import java.awt.Color;
import Route.CreateVehicleRoute;
import Route.ViewVehicleRoute;
import Staff.Staff;
import Staff.StaffDetails;
import Vehicle.FullVehicleDetails;
import Vehicle.Vehicle_RegistrationInterface;
import javax.swing.JFrame;

/**
 *
 * @author sachintha
 */
public class PassengerHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private static String name;
    public PassengerHome(String name) {
        initComponents();
        this.name = name;
        jLabel1.setText("Welcome   "+name);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        panelTicket.setVisible(false);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tab7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tab8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelTicket = new javax.swing.JPanel();
        tab14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tab15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelVehicle = new javax.swing.JPanel();
        tab18 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        panelRoute = new javax.swing.JPanel();
        tab20 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab2.setBackground(new java.awt.Color(255, 204, 153));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("TICKET");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel2.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 286, 314, -1));

        tab3.setBackground(new java.awt.Color(255, 204, 153));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("VEHICLE");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(94, 94, 94))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 354, 314, -1));

        tab4.setBackground(new java.awt.Color(255, 204, 153));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("ROUTE");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.add(tab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 427, 314, -1));

        tab6.setBackground(new java.awt.Color(255, 204, 153));
        tab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab6MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 51, 0));
        jLabel6.setText("CONTACT US");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab6Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(50, 50, 50))
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab6Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.add(tab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 551, 310, -1));

        tab7.setBackground(new java.awt.Color(255, 204, 153));
        tab7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab7MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("ABOUT US");

        javax.swing.GroupLayout tab7Layout = new javax.swing.GroupLayout(tab7);
        tab7.setLayout(tab7Layout);
        tab7Layout.setHorizontalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab7Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(67, 67, 67))
        );
        tab7Layout.setVerticalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(tab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 613, 310, -1));

        tab8.setBackground(new java.awt.Color(255, 102, 102));
        tab8.setForeground(new java.awt.Color(255, 255, 255));
        tab8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab8MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOG OUT");

        javax.swing.GroupLayout tab8Layout = new javax.swing.GroupLayout(tab8);
        tab8.setLayout(tab8Layout);
        tab8Layout.setHorizontalGroup(
            tab8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab8Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab8Layout.setVerticalGroup(
            tab8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel2.add(tab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 676, 314, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tour_Management_System/LOGO.png"))); // NOI18N
        jLabel9.setText("       ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 41, 172, 194));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTicket.setBackground(new java.awt.Color(0, 153, 204));

        tab14.setBackground(new java.awt.Color(255, 204, 153));
        tab14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab14MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 51, 0));
        jLabel13.setText("BOOK");

        javax.swing.GroupLayout tab14Layout = new javax.swing.GroupLayout(tab14);
        tab14.setLayout(tab14Layout);
        tab14Layout.setHorizontalGroup(
            tab14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab14Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel13)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        tab14Layout.setVerticalGroup(
            tab14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab15.setBackground(new java.awt.Color(255, 204, 153));
        tab15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab15MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 51, 0));
        jLabel14.setText("VIEW TICKETS");

        javax.swing.GroupLayout tab15Layout = new javax.swing.GroupLayout(tab15);
        tab15.setLayout(tab15Layout);
        tab15Layout.setHorizontalGroup(
            tab15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab15Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(28, 28, 28))
        );
        tab15Layout.setVerticalGroup(
            tab15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTicketLayout = new javax.swing.GroupLayout(panelTicket);
        panelTicket.setLayout(panelTicketLayout);
        panelTicketLayout.setHorizontalGroup(
            panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(tab15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        panelTicketLayout.setVerticalGroup(
            panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTicketLayout.createSequentialGroup()
                .addGroup(panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(panelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        panelVehicle.setBackground(new java.awt.Color(0, 153, 204));

        tab18.setBackground(new java.awt.Color(255, 204, 153));
        tab18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab18MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 51, 0));
        jLabel17.setText("VEW VEHICLE");

        javax.swing.GroupLayout tab18Layout = new javax.swing.GroupLayout(tab18);
        tab18.setLayout(tab18Layout);
        tab18Layout.setHorizontalGroup(
            tab18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab18Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel17)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        tab18Layout.setVerticalGroup(
            tab18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelVehicleLayout = new javax.swing.GroupLayout(panelVehicle);
        panelVehicle.setLayout(panelVehicleLayout);
        panelVehicleLayout.setHorizontalGroup(
            panelVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(617, Short.MAX_VALUE))
        );
        panelVehicleLayout.setVerticalGroup(
            panelVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehicleLayout.createSequentialGroup()
                .addComponent(tab18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(panelVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        panelRoute.setBackground(new java.awt.Color(0, 153, 204));

        tab20.setBackground(new java.awt.Color(255, 204, 153));
        tab20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab20MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 51, 0));
        jLabel19.setText("VIEW ROUTE");

        javax.swing.GroupLayout tab20Layout = new javax.swing.GroupLayout(tab20);
        tab20.setLayout(tab20Layout);
        tab20Layout.setHorizontalGroup(
            tab20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab20Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel19)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        tab20Layout.setVerticalGroup(
            tab20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRouteLayout = new javax.swing.GroupLayout(panelRoute);
        panelRoute.setLayout(panelRouteLayout);
        panelRouteLayout.setHorizontalGroup(
            panelRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRouteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(587, Short.MAX_VALUE))
        );
        panelRouteLayout.setVerticalGroup(
            panelRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRouteLayout.createSequentialGroup()
                .addComponent(tab20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(panelRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 880, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Welcome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        
        panelTicket.setVisible(true);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(false);
   
      
        

        tab2.setBackground(Color.WHITE);
        tab3.setBackground(new Color(255,204,153));
        tab4.setBackground(new Color(255,204,153));
        tab6.setBackground(new Color(255,204,153));
        tab7.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        
      
        panelTicket.setVisible(false);
        panelVehicle.setVisible(true);
        panelRoute.setVisible(false);

    
     
        
    
        tab2.setBackground(new Color(255,204,153));
        tab3.setBackground(Color.WHITE);
        tab4.setBackground(new Color(255,204,153));
        tab6.setBackground(new Color(255,204,153));
        tab7.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        

        panelTicket.setVisible(false);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(true);
     
     
        

        tab2.setBackground(new Color(255,204,153));
        tab3.setBackground(new Color(255,204,153));
        tab4.setBackground(Color.WHITE);
        tab6.setBackground(new Color(255,204,153));
        tab7.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_tab4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
     
        panelTicket.setVisible(false);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(false);
     
      
        
   
        tab2.setBackground(new Color(255,204,153));
        tab3.setBackground(new Color(255,204,153));
        tab4.setBackground(new Color(255,204,153));
        tab6.setBackground(Color.WHITE);
        tab7.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tab7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab7MouseClicked

        panelTicket.setVisible(false);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(false);
       
     

        tab2.setBackground(new Color(255,204,153));
        tab3.setBackground(new Color(255,204,153));
        tab4.setBackground(new Color(255,204,153));
        tab6.setBackground(new Color(255,204,153));
        tab7.setBackground(Color.WHITE);
        
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_tab7MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void tab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab6MouseClicked
        Contact newContact = new Contact();
        newContact.setVisible(true);
    }//GEN-LAST:event_tab6MouseClicked

    private void tab14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab14MouseClicked
        FindVehicle findVehicle = new FindVehicle();
        findVehicle.setVisible(true);
    }//GEN-LAST:event_tab14MouseClicked

    private void tab15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab15MouseClicked
        ViewTickets tickets = new ViewTickets();
        tickets.setVisible(true);
    }//GEN-LAST:event_tab15MouseClicked

    private void tab20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab20MouseClicked
       ViewVehicleRoute viewRoute = new ViewVehicleRoute();
        viewRoute.setVisible(true);
    }//GEN-LAST:event_tab20MouseClicked

    private void tab18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab18MouseClicked
        FullVehicleDetails vehicleDetails = new FullVehicleDetails();
       vehicleDetails.setVisible(true);

    }//GEN-LAST:event_tab18MouseClicked

    private void tab8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab8MouseClicked
       PassengerLogin passengerLogin = new  PassengerLogin();
       passengerLogin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tab8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerHome(name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPanel panelRoute;
    private javax.swing.JPanel panelTicket;
    private javax.swing.JPanel panelVehicle;
    private javax.swing.JPanel tab14;
    private javax.swing.JPanel tab15;
    private javax.swing.JPanel tab18;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab20;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab6;
    private javax.swing.JPanel tab7;
    private javax.swing.JPanel tab8;
    // End of variables declaration//GEN-END:variables
}
