/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tour_Management_System;

import AboutUs.About;
import java.awt.Color;
import Route.CreateVehicleRoute;
import Route.ViewVehicleRoute;
import Staff.Staff;
import Staff.StaffDetails;
import Vehicle.FullVehicleDetails;
import Vehicle.Vehicle_RegistrationInterface;
import javax.swing.JFrame;

/**
 *
 * @author sachintha
 */
public class StaffHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private static String name;
    public StaffHome(String name) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.name = name;
        panelStaff.setVisible(false);
        panelTicket.setVisible(false);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tab8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelStaff = new javax.swing.JPanel();
        tab12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tab13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panelTicket = new javax.swing.JPanel();
        tab14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tab15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelVehicle = new javax.swing.JPanel();
        tab18 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tab19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panelRoute = new javax.swing.JPanel();
        tab20 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tab21 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setBackground(new java.awt.Color(255, 204, 153));
        tab1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tab1MouseMoved(evt);
            }
        });
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab1MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("STAFF");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, 314, -1));

        tab2.setBackground(new java.awt.Color(255, 204, 153));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("TICKET");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel2.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 286, 314, -1));

        tab3.setBackground(new java.awt.Color(255, 204, 153));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("VEHICLE");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(94, 94, 94))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 354, 314, -1));

        tab4.setBackground(new java.awt.Color(255, 204, 153));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("ROUTE");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.add(tab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 427, 314, -1));

        tab7.setBackground(new java.awt.Color(255, 204, 153));
        tab7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab7MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("ABOUT US");

        javax.swing.GroupLayout tab7Layout = new javax.swing.GroupLayout(tab7);
        tab7.setLayout(tab7Layout);
        tab7Layout.setHorizontalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab7Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(72, 72, 72))
        );
        tab7Layout.setVerticalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel2.add(tab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 613, 310, -1));

        tab8.setBackground(new java.awt.Color(255, 102, 102));
        tab8.setForeground(new java.awt.Color(255, 255, 255));
        tab8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab8MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOG OUT");

        javax.swing.GroupLayout tab8Layout = new javax.swing.GroupLayout(tab8);
        tab8.setLayout(tab8Layout);
        tab8Layout.setHorizontalGroup(
            tab8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab8Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab8Layout.setVerticalGroup(
            tab8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel2.add(tab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 676, 314, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tour_Management_System/LOGO.png"))); // NOI18N
        jLabel9.setText("       ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, 172, 194));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelStaff.setBackground(new java.awt.Color(0, 153, 204));

        tab12.setBackground(new java.awt.Color(255, 204, 153));
        tab12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tab12MouseMoved(evt);
            }
        });
        tab12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab12MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 51, 0));
        jLabel11.setText("ADD NEW");

        javax.swing.GroupLayout tab12Layout = new javax.swing.GroupLayout(tab12);
        tab12.setLayout(tab12Layout);
        tab12Layout.setHorizontalGroup(
            tab12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab12Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel11)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        tab12Layout.setVerticalGroup(
            tab12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tab13.setBackground(new java.awt.Color(255, 204, 153));
        tab13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tab13MouseMoved(evt);
            }
        });
        tab13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tab13MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 51, 0));
        jLabel12.setText("VIEW DATA");

        javax.swing.GroupLayout tab13Layout = new javax.swing.GroupLayout(tab13);
        tab13.setLayout(tab13Layout);
        tab13Layout.setHorizontalGroup(
            tab13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab13Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(48, 48, 48))
        );
        tab13Layout.setVerticalGroup(
            tab13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelStaffLayout = new javax.swing.GroupLayout(panelStaff);
        panelStaff.setLayout(panelStaffLayout);
        panelStaffLayout.setHorizontalGroup(
            panelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(tab13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStaffLayout.setVerticalGroup(
            panelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStaffLayout.createSequentialGroup()
                .addGroup(panelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tab12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(panelStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 70));

        panelTicket.setBackground(new java.awt.Color(0, 153, 204));

        tab14.setBackground(new java.awt.Color(255, 204, 153));
        tab14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab14MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 51, 0));
        jLabel13.setText("BOOK");

        javax.swing.GroupLayout tab14Layout = new javax.swing.GroupLayout(tab14);
        tab14.setLayout(tab14Layout);
        tab14Layout.setHorizontalGroup(
            tab14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab14Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel13)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        tab14Layout.setVerticalGroup(
            tab14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab15.setBackground(new java.awt.Color(255, 204, 153));
        tab15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab15MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 51, 0));
        jLabel14.setText("VIEW TICKETS");

        javax.swing.GroupLayout tab15Layout = new javax.swing.GroupLayout(tab15);
        tab15.setLayout(tab15Layout);
        tab15Layout.setHorizontalGroup(
            tab15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab15Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(28, 28, 28))
        );
        tab15Layout.setVerticalGroup(
            tab15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTicketLayout = new javax.swing.GroupLayout(panelTicket);
        panelTicket.setLayout(panelTicketLayout);
        panelTicketLayout.setHorizontalGroup(
            panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(tab15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        panelTicketLayout.setVerticalGroup(
            panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTicketLayout.createSequentialGroup()
                .addGroup(panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(panelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        panelVehicle.setBackground(new java.awt.Color(0, 153, 204));

        tab18.setBackground(new java.awt.Color(255, 204, 153));
        tab18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab18MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 51, 0));
        jLabel17.setText("ADD NEW");

        javax.swing.GroupLayout tab18Layout = new javax.swing.GroupLayout(tab18);
        tab18.setLayout(tab18Layout);
        tab18Layout.setHorizontalGroup(
            tab18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab18Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel17)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        tab18Layout.setVerticalGroup(
            tab18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        tab19.setBackground(new java.awt.Color(255, 204, 153));
        tab19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab19MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 51, 0));
        jLabel18.setText("VIEW DATA");

        javax.swing.GroupLayout tab19Layout = new javax.swing.GroupLayout(tab19);
        tab19.setLayout(tab19Layout);
        tab19Layout.setHorizontalGroup(
            tab19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab19Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(55, 55, 55))
        );
        tab19Layout.setVerticalGroup(
            tab19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelVehicleLayout = new javax.swing.GroupLayout(panelVehicle);
        panelVehicle.setLayout(panelVehicleLayout);
        panelVehicleLayout.setHorizontalGroup(
            panelVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(tab19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        panelVehicleLayout.setVerticalGroup(
            panelVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehicleLayout.createSequentialGroup()
                .addGroup(panelVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(panelVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        panelRoute.setBackground(new java.awt.Color(0, 153, 204));

        tab20.setBackground(new java.awt.Color(255, 204, 153));
        tab20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab20MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 51, 0));
        jLabel19.setText("CREATE ROUTE");

        javax.swing.GroupLayout tab20Layout = new javax.swing.GroupLayout(tab20);
        tab20.setLayout(tab20Layout);
        tab20Layout.setHorizontalGroup(
            tab20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab20Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel19)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        tab20Layout.setVerticalGroup(
            tab20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab21.setBackground(new java.awt.Color(255, 204, 153));
        tab21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab21MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("LM Sans 8", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 51, 0));
        jLabel20.setText("VIEW ROUTE");

        javax.swing.GroupLayout tab21Layout = new javax.swing.GroupLayout(tab21);
        tab21.setLayout(tab21Layout);
        tab21Layout.setHorizontalGroup(
            tab21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab21Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel20)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        tab21Layout.setVerticalGroup(
            tab21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRouteLayout = new javax.swing.GroupLayout(panelRoute);
        panelRoute.setLayout(panelRouteLayout);
        panelRouteLayout.setHorizontalGroup(
            panelRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRouteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(tab21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        panelRouteLayout.setVerticalGroup(
            panelRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRouteLayout.createSequentialGroup()
                .addGroup(panelRouteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(panelRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 880, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseEntered
         
    }//GEN-LAST:event_tab1MouseEntered

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        panelStaff.setVisible(true);
        panelTicket.setVisible(false);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(false);
     
       
        tab1.setBackground(Color.WHITE);
        tab2.setBackground(new Color(255,204,153));
        tab3.setBackground(new Color(255,204,153));
        tab4.setBackground(new Color(255,204,153));
        tab7.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_tab1MouseClicked

    private void tab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseExited

    }//GEN-LAST:event_tab1MouseExited

    private void tab1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseMoved
          
    }//GEN-LAST:event_tab1MouseMoved

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        
        panelStaff.setVisible(false);
        panelTicket.setVisible(true);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(false);

      
        
        tab1.setBackground(new Color(255,204,153));
        tab2.setBackground(Color.WHITE);
        tab3.setBackground(new Color(255,204,153));
        tab4.setBackground(new Color(255,204,153));
        tab7.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        
        panelStaff.setVisible(false);
        panelTicket.setVisible(false);
        panelVehicle.setVisible(true);
        panelRoute.setVisible(false);

     
        
        tab1.setBackground(new Color(255,204,153));
        tab2.setBackground(new Color(255,204,153));
        tab3.setBackground(Color.WHITE);
        tab4.setBackground(new Color(255,204,153));
        tab7.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        
        panelStaff.setVisible(false);
        panelTicket.setVisible(false);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(true);
     
        
        tab1.setBackground(new Color(255,204,153));
        tab2.setBackground(new Color(255,204,153));
        tab3.setBackground(new Color(255,204,153));
        tab4.setBackground(Color.WHITE);
        tab7.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_tab4MouseClicked

    private void tab7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab7MouseClicked
        
        panelStaff.setVisible(false);
        panelTicket.setVisible(false);
        panelVehicle.setVisible(false);
        panelRoute.setVisible(false);
     
        tab1.setBackground(new Color(255,204,153));
        tab2.setBackground(new Color(255,204,153));
        tab3.setBackground(new Color(255,204,153));
        tab4.setBackground(new Color(255,204,153));
        tab7.setBackground(Color.WHITE);
        
         About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_tab7MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void tab8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab8MouseClicked
       Login   login = new Login();
       login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tab8MouseClicked

    private void tab21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab21MouseClicked
        ViewVehicleRoute viewRoute = new ViewVehicleRoute();
        viewRoute.setVisible(true);
    }//GEN-LAST:event_tab21MouseClicked

    private void tab20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab20MouseClicked
        CreateVehicleRoute vehicleRoute = new CreateVehicleRoute();
        vehicleRoute.setVisible(true);
    }//GEN-LAST:event_tab20MouseClicked

    private void tab19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab19MouseClicked
        FullVehicleDetails vehicleDetails = new FullVehicleDetails();
        vehicleDetails.setVisible(true);
    }//GEN-LAST:event_tab19MouseClicked

    private void tab18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab18MouseClicked
        Vehicle_RegistrationInterface vehicle = new Vehicle_RegistrationInterface();
        vehicle.setVisible(true);

    }//GEN-LAST:event_tab18MouseClicked

    private void tab15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab15MouseClicked
        ViewTickets tickets = new ViewTickets();
        tickets.setVisible(true);
    }//GEN-LAST:event_tab15MouseClicked

    private void tab14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab14MouseClicked
        FindVehicle findVehicle = new FindVehicle();
        findVehicle.setVisible(true);
    }//GEN-LAST:event_tab14MouseClicked

    private void tab13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tab13MouseExited

    private void tab13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tab13MouseEntered

    private void tab13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab13MouseClicked
        StaffDetails details = new StaffDetails();
        details.setVisible(true);
    }//GEN-LAST:event_tab13MouseClicked

    private void tab13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab13MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tab13MouseMoved

    private void tab12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tab12MouseExited

    private void tab12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tab12MouseEntered

    private void tab12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab12MouseClicked
        Staff staff = new Staff();
        staff.setVisible(true);
    }//GEN-LAST:event_tab12MouseClicked

    private void tab12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab12MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tab12MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffHome(name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPanel panelRoute;
    private javax.swing.JPanel panelStaff;
    private javax.swing.JPanel panelTicket;
    private javax.swing.JPanel panelVehicle;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab12;
    private javax.swing.JPanel tab13;
    private javax.swing.JPanel tab14;
    private javax.swing.JPanel tab15;
    private javax.swing.JPanel tab18;
    private javax.swing.JPanel tab19;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab20;
    private javax.swing.JPanel tab21;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab7;
    private javax.swing.JPanel tab8;
    // End of variables declaration//GEN-END:variables
}
